adding param FromBlock and ToBlock
zoobc/zoobc-core pull request #1439
Opened 2021-01-20 07:51 UTC by KevinH2810

2021-01-20 08:21 UTC, capt4ce requested changes

2021-01-20 08:21 UTC, capt4ce commented on api/service/transactionApiService.go
> +	}
I think we need to improve the validation, if it's like this, we won't be able to get block starting from height 0. can we have a better validation?

2021-01-21 02:26 UTC, capt4ce reviewed
is it necessary to update the go mod and go sum?

2021-01-21 03:31 UTC, KevinH2810 commented on api/service/transactionApiService.go
> +	}
i have add some more validation for 0 Height and if fromBlock is greater than the toBlock the throw err

2021-01-21 15:14 UTC, closed without merging